### ISSUE TITLE
DRV8830

### ISSUE THREAD

**Issue by samuk** [platisd/smartcar_shield#62]
## Description

Would you be interested in supporting https://github.com/adafruit/Adafruit_DRV8830 under your library?

**Comment by platisd** [comment]
Sure, why not? The placeholder I2cMotor class was created with something like that in mind.

**Comment by samuk** [comment]
Great! This is the one I'd use https://shop.pimoroni.com/products/drv8830-dc-motor-driver-breakout?variant=30093450739795 there are a few available

**Comment by platisd** [comment]
I suggest the following steps forward since I don't have this piece of HW:
1. Get your hands on the hardware
2. Make it work with some library/code
3. Send me a link to that library/code (please do not use software that's licensed under GPL) along with exactly what address were used etc.
4. I integrate it to this library

Does that sound good?

**Comment by samuk** [comment]
Great!
